[package]
name = "bpxc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
bpx = { version = "4.0.0-beta-7.2.2", features = ["sd"] }
libc = "0.2.125"
